CREATE VIEW nbl_ddi_supply_chain.fact_service_metrics_v (
  HISTORY_TYPE,
  WEEK_NUMBER,
  TRIP_ID,
  NUMBER_OF_STOPS,
  CUSTOMER_NAME,
  CUSTOMER_PO_NUMBER,
  ORDER_NUMBER,
  LINE_NUMBER,
  DELIVERY_NUMBER,
  FREIGHT_METHOD,
  SHIP_FROM_ORG,
  ITEM_NUMBER,
  UOM,
  QTY_REQUESTED,
  REQUESTED_24PKEQCASES,
  QTY_SHIPPED,
  SHIPPED_24PKEQCASES,
  QTY_SHORT_SHIPPED,
  PKEQ24_CASES_SHORT_SHIPPED,
  SHORT_SHIP_REASON_CODE,
  RESCHEDULE_REASON_CODE,
  REQUEST_DATE_FROM,
  REQUEST_DATE_TO,
  FINAL_REQUEST_DATE_LOCAL,
  ORIGINAL_REQUEST_DATE_LOCAL,
  ORIGINAL_SCHEDULE_SHIP_DATE,
  PROMISE_DATE_FROM,
  PROMISE_DATE_TO,
  FINAL_PROMISE_DATE_LOCAL,
  SHIP_CONFIRM_DATE_LOCAL,
  PICKUP_APPOINTMENT_LOCAL,
  DELIVERY_APPOINTMENT_LOCAL,
  LINE_ITEM_STATUS,
  CANCEL_REASON_CODE,
  USER_NAME,
  HISTORICAL_CREATION_DATE_PST,
  LAST_STOP_ACTUAL_ARRIVAL,
  SHIP_TO_CITY,
  SHIP_TO_STATE,
  SHIP_TO_ZIPCODE,
  PARTY_SITE_NUMBER,
  SALES_CHANNEL_CODE,
  DTS_FLAG,
  LOCATION_TYPE,
  CARRIER_NAME,
  ORDER_CREATION_DATE_PST,
  SHIPMENT_GID,
  ORDER_HEADER_STATUS,
  BOTTLE_SIZE,
  PACK_SIZE,
  PRODUCT,
  PRODUCT_FAMILY,
  PRODUCT_CATEGORY,
  PRODUCT_CATEGORY_SC,
  SALES_CATEGORY,
  REASON_COMMENTS,
  TRANSPORT_MODE_GID,
  DROP_FLAG,
  EARLY_DELIVERY_DATE,
  LATE_DELIVERY_DATE,
  DELIVERY_WINDOW_START_LOCAL,
  DELIVERY_WINDOW_END_LOCAL,
  LATEST_CHANGE_FILTER,
  ITEM_ONDATE,
  QTY_CORRECT,
  LEAD_TIME_DAYS,
  RECOVERY_TIME_DAYS,
  ORDER_COUNTER,
  ITEM_COUNTER,
  PUSH_PULL_FLAG,
  SHIPMENT_COUNTER,
  CHANGE_COUNTER,
  SHIP_FROM_ROLLUP_ORG,
  SHIP_FROM_SC_REGION,
  DOMAIN_NAME,
  SHIP_TO_COUNTRY,
  CHANGE_TYPE,
  ORDER_CREATION_DATE_DEST,
  PICKUP_APPOINTMENT_DEST,
  BUFFERED_DELIVERY_TIME_LOCAL,
  ITEM_ONTIME,
  CONTRACTUAL_LEAD_TIME_DAYS,
  CS_TEAM,
  CUSTOMER_REGION,
  DEST_LOCATION_GID,
  PROMISE_YEAR,
  DEPLOYMENT_FLAG,
  REQUESTED_CASES,
  SHIPPED_CASES,
  SHORT_CASES,
  SHIP_FROM_SHIPPING_REGION,
  CS_REPS,
  OR_SCHEDULE_FLAG,
  STATUS_TYPE_GID,
  STATUS_VALUE_GID,
  SALES_REGION,
  OR_RATE_OFFERING_GID,
  OR_INDICATOR,
  FINAL_REQUEST_YEAR,
  FINAL_REQUEST_WEEK,
  OR_RATE_GEO_GID,
  SH_X_LANE_GID,
  OR_TRANSPORT_MODE_GID,
  OR_DEPLOYMENT_FLAG,
  DISTANCE,
  OR_PENDING_REASON,
  SH_RATE_OFFERING_GID,
  SH_RATE_GEO_GID,
  X_LANE_GID,
  SH_TRANSPORT_MODE_GID,
  CANCELLED_QUANTITY,
  PKEQ24_CANCELLED_CASES,
  SCHEDULE_INSERT_DATE_LOCAL,
  SCHEDULE_INSERT_DATE_PST,
  SCHEDULE_UPDATE_DATE_LOCAL,
  SCHEDULE_UPDATE_DATE_PST,
  SCHEDULE_UPDATE_USER,
  ORIGINAL_REQUEST_YEAR,
  ORIGINAL_REQUEST_WEEK,
  CPU_CONTACT,
  SHIP_TO_ADDRESS,
  CHECK_IN_TIME_LOCAL,
  CHECK_IN_TIME_PST,
  CHECK_OUT_TIME_LOCAL,
  CHECK_OUT_TIME_PST,
  DOCK_DOOR,
  DOCK_DOOR_ALLOCATION,
  SHIPMENT_START_DATE_PST,
  FIRST_LOAD_TIME,
  LAST_LOAD_TIME,
  LOAD_TYPE,
  CLOSE_TRAILER,
  CLOSE_TRAILER_LOCAL,
  FG_BRAND,
  PRODUCT_TYPE,
  FG_FLAVOR,
  FG_SALES_CATEGORY,
  FG_BUSINESS_UNIT,
  DEF_SHIP_FROM_ORG,
  ORDER_RELEASE_INSERT_DATE_PST,
  CUSTOMER_ITEM,
  DESTINATION_DEPARTURE214,
  DEF_SHIP_FROM_ROLLUP_ORG,
  ORDER_TYPE_CODE,
  SHIP_TO_ORG,
  SHIP_TO_ROLLUP_ORG,
  SHIP_TO_SC_REGION,
  FIRST_RESCHEDULE_REASON_CODE,
  ITEM_DESCRIPTION,
  SHIP_CONFIRM_YEAR,
  SHIP_CONFIRM_WEEK,
  LOCATION,
  SOA_SHIPMENT_TIME,
  SOA_SHIPMENT_WEEK,
  SOA_SHIPMENT_YEAR,
  SOA_SHORT_SHIPPED_CASES,
  SOA_SHIPPED_24PKEQCASES,
  SOA_SHORT_SHIPPED_24PKEQCASES,
  X_ATTRIBUTE14,
  ORIGINAL_REQUESTED_CASES,
  ORIGINAL_REQUESTED_24PKEQCASES,
  SHIP_TO_SH_REGION,
  SUPPLY_CHAIN_LOAD_TYPE,
  CANCEL_REASON_BUCKET,
  REQUESTED_PALLETS,
  SHIPPED_PALLETS,
  SHORT_PALLETS,
  CANCELLED_CASES,
  CANCELLED_24PKEQCASES,
  CANCELLED_PALLETS,
  DELIVERY_APPOINTMENT_PST,
  DELIVERY_WINDOW_END_PST,
  DELIVERY_WINDOW_START_PST,
  LAST_STOP_ACTUAL_DEPARTURE,
  ORDER_CREATION_DATE_LOCAL,
  ORIGINAL_REQUEST_DATE_PST,
  PICKUP_APPOINTMENT_PST,
  SHORT_24PKEQCASES,
  SHIP_CONFIRM_DATE_PST,
  WATER_TYPE_SC,
  PROMISE_WEEK,
  CRITICAL_FLAG,
  DEMAND_CLASS_CODE,
  AOP_RESULT,
  GENPLAN_RESULT,
  SHIPMENT_PRELOAD,
  SOA_SHIPPED_CASES,
  LINE_CREATED_ON_DT,
  SCHEDULE_INSERT_DATE,
  SCHEDULE_UPDATE_DATE,
  OREF_SCHEDULE_UPDATE_DATE,
  OREF_SCHEDULE_INSERT_USER,
  OREF_SCHEDULE_UPDATE_DATE_LOCAL,
  OREF_SCHEDULE_INSERT_DATE_LOCAL,
  OREF_SCHEDULE_UPDATE_DATE_PST,
  OREF_SCHEDULE_INSERT_DATE_PST,
  WITH_DRAW_USER_FLAG,
  BALANCE_REQUESTED_CASES,
  FINAL_REQUEST_DATE_PST,
  ROLLUP_ITEM,
  MTO_FLG,
  OSP,
  MOSP,
  PUA_REASON_CODE,
  SOA_SHIPMENT_DATE_LOCAL,
  SOA_SHIPMENT_DATE_PST,
  FINAL_PROMISE_DATE_PST,
  LAST_STOP_ACTUAL_ARRIVAL_LOCAL,
  ORDER_RELEASE_INSERT_DATE,
  ORDERED_ON_DT,
  EARLY_PICKUP_DATE)
WITH SCHEMA COMPENSATION
AS SELECT
  S.HISTORY_TYPE,
  S.WEEK_NUMBER,
  s.TRIP_ID,
  S.STOP_NUMBER NUMBER_OF_STOPS,
  S.CUSTOMER CUSTOMER_NAME,
  S.CUST_PO CUSTOMER_PO_NUMBER,
  S.ORDER_NUMBER,
  S.LINE_NUMBER,
  S.DELIVERY_NUMBER DELIVERY_NUMBER,
  S.FREIGHT_METHOD,
  S.ORGANIZATION_CODE SHIP_FROM_ORG,
  S.ITEM ITEM_NUMBER,
  S.UOM,
  S.QTY_REQUESTED,
  S.PKEQ24_CASES_REQUESTED REQUESTED_24PKEQCASES,
  S.QTY_SHIPPED AS QTY_SHIPPED,
  S.PKEQ24_CASES_SHIPPED SHIPPED_24PKEQCASES,
  S.QTY_SHORT_SHIPPED AS QTY_SHORT_SHIPPED,
  S.PKEQ24_CASES_SHORT_SHIPPED AS PKEQ24_CASES_SHORT_SHIPPED,
  S.SHORT_SHIP_REASON_CODE AS SHORT_SHIP_REASON_CODE,
  S.DATE_CHANGE_REASON_CODE RESCHEDULE_REASON_CODE,
  S.REQUEST_DATE_FROM,
  S.REQUEST_DATE_TO,
  S.FINAL_REQUEST_DATE FINAL_REQUEST_DATE_LOCAL,
  S.ORIGINAL_REQUEST_DATE ORIGINAL_REQUEST_DATE_LOCAL,
  S.ORIGINAL_SCHEDULE_SHIP_DATE,
  S.CUSTOMER_AGREED_DATE_FROM PROMISE_DATE_FROM,
  S.CUSTOMER_AGREED_DATE_TO PROMISE_DATE_TO,
  S.FINAL_CUSTOMER_AGREED_DATE FINAL_PROMISE_DATE_LOCAL,
  S.SHIP_CONFIRM_DATE_LOCAL SHIP_CONFIRM_DATE_LOCAL,
  S.PICKUP_APPOINTMENT PICKUP_APPOINTMENT_LOCAL,
  S.DELIVERY_APPOINTMENT DELIVERY_APPOINTMENT_LOCAL,
  S.STATUS LINE_ITEM_STATUS,
  S.CANCEL_REASON_CODE,
  S.USERNAME USER_NAME,
  S.HIST_CREATION_DATE HISTORICAL_CREATION_DATE_PST,
  S.LOCAL_ARRIVAL_DATE_214 LAST_STOP_ACTUAL_ARRIVAL,
  S.SHIP_TO_CITY,
  S.SHIP_TO_STATE,
  S.ZIP_CODE SHIP_TO_ZIPCODE,
  S.PARTY_SITE_NUMBER,
  S.SALES_CHANNEL_CODE,
  S.DTS_FLAG,
  S.DTS_DC_CLASSIFICATION LOCATION_TYPE,
  S.CARRIER_NAME,
  S.ORDER_CREATION_DATE ORDER_CREATION_DATE_PST,
  S.SHIPMENT_GID,
  S.ORDER_HEADER_STATUS,
  S.BOTTLE_SIZE BOTTLE_SIZE,
  S.PACKAGE_SIZE PACK_SIZE,
  S.PRODUCT,
  S.PRODUCT_FAMILY,
  S.PRODUCT_CATEGORY,
  S.PRODUCT_CATEGORY_SC PRODUCT_CATEGORY_SC,
  DECODE(I.PRODUCT_TYPE_CODE, 'SA', I.X_PRODUCT, I.X_FG_SALES_CATGORY) SALES_CATEGORY,
  S.REASON_COMMENTS,
  S.TRANSPORT_MODE_GID,
  S.SHIPMENT_DROP DROP_FLAG,
  S.EARLY_DELIVERY_DATE,
  S.LATE_DELIVERY_DATE,
  S.DELIVERY_WINDOW_START DELIVERY_WINDOW_START_LOCAL,
  S.DELIVERY_WINDOW_END DELIVERY_WINDOW_END_LOCAL,
  S.LATEST_CHANGE_FILTER,
  S.ITEM_CUSTOMER_WANT_DATE ITEM_ONDATE,
  S.QTY_CORRECT,
  S.LEAD_TIME_DAYS,
  S.RECOVERY_TIME_DAYS,
  S.ORDER_COUNTER,
  S.ITEM_COUNTER,
  S.PUSH_PULL_FLAG,
  S.SHIPMENT_COUNTER,
  S.CHANGE_COUNTER,
  S.ROLLUP_ORGANIZATION_CODE SHIP_FROM_ROLLUP_ORG,
  S.SUPPLY_CHAIN_REGION SHIP_FROM_SC_REGION,
  S.DOMAIN_NAME DOMAIN_NAME,
  S.SHIP_TO_COUNTRY,
  S.CHANGE_TYPE,
  S.DEST_ORDER_CREATION_DATE ORDER_CREATION_DATE_DEST,
  S.DEST_PICKUP_APPOINTMENT PICKUP_APPOINTMENT_DEST,
  S.BUFFERED_APPOINTMENT_TIME BUFFERED_DELIVERY_TIME_LOCAL,
  S.ITEM_ON_TIME ITEM_ONTIME,
  S.CONTRACTUAL_LEAD_TIME CONTRACTUAL_LEAD_TIME_DAYS,
  S.CS_TEAM,
  (
    SELECT DISTINCT
      SITE.CUSTOMER_REGION
    FROM
      NBL_FUSION_DW.DIM_CUST_SITE_USE SITE
    WHERE
      SITE.SK_CUST_SITE_USE_ID = S.SK_X_SHIP_TO_ORG_ID
    LIMIT 1
  ) AS CUSTOMER_REGION,
  S.CUSTOMER_LOCATION_GID DEST_LOCATION_GID,
  S.YEAR_NUMBER PROMISE_YEAR,
  S.DEPLOYMENT_FLAG,
  S.ACTUAL_CASES_REQUESTED REQUESTED_CASES,
  S.ACTUAL_CASES_SHIPPED SHIPPED_CASES,
  S.ACTUAL_CASES_SHORT_SHIPPED SHORT_CASES,
  S.SHIPPING_REGION SHIP_FROM_SHIPPING_REGION,
  S.CS_REPS,
  S.OR_USER_DEFINED1_ICON_GID OR_SCHEDULE_FLAG,
  S.STATUS_TYPE_GID,
  S.STATUS_VALUE_GID,
  S.NIAGARA_SALES_REGION SALES_REGION,
  S.OR_RATE_OFFERING_GID,
  S.ORDER_RELEASE_INDICATOR OR_INDICATOR,
  S.FINAL_REQUEST_YEAR,
  S.FINAL_REQUEST_WEEK,
  S.RATE_GEO_GID OR_RATE_GEO_GID,
  S.SH_X_LANE_GID,
  S.OR_TRANSPORTATION_MODE_GID OR_TRANSPORT_MODE_GID,
  S.SH_DEPLOYMENT_FLAG OR_DEPLOYMENT_FLAG,
  S.FINAL_MILES DISTANCE,
  S.OR_PENDING_REASON,
  S.SH_RATE_OFFERING_GID,
  S.SH_RATE_GEO_GID,
  S.X_LANE_GID,
  S.SH_TRANSPORTATION_MODE_GID SH_TRANSPORT_MODE_GID,
  S.CANCELLED_QUANTITY,
  S.CANCELLED_QUANTITY
  * CAST(
    CASE
      WHEN I.X_ATTRIBUTE5 = '-' THEN 0
      ELSE I.X_ATTRIBUTE5
    END AS DOUBLE
  ) AS PKEQ24_CANCELLED_CASES,
  S.SCHEDULE_INSERT_DATE_LOCAL,
  S.SCHEDULE_INSERT_DATE_PST,
  S.SCHEDULE_UPDATE_DATE_LOCAL,
  S.SCHEDULE_UPDATE_DATE_PST,
  S.SCHEDULE_UPDATE_USER,
  S.ORIGINAL_REQUEST_YEAR,
  S.ORIGINAL_REQUEST_WEEK,
  S.CPU_CONTRACT CPU_CONTACT,
  S.ADDRESS SHIP_TO_ADDRESS,
  S.CHECK_IN_TIME_LOCAL CHECK_IN_TIME_LOCAL,
  S.CHECK_IN_TIME CHECK_IN_TIME_PST,
  S.CHECK_OUT_TIME_LOCAL CHECK_OUT_TIME_LOCAL,
  S.CHECK_OUT_TIME CHECK_OUT_TIME_PST,
  S.DOCK_DOOR,
  S.DOCK_DOOR_ALLOCATION,
  S.STARTDATETIME SHIPMENT_START_DATE_PST,
  S.FIRST_LOAD_TIME,
  S.LAST_LOAD_TIME,
  S.LOAD_TYPE,
  S.CLOSE_TRAILER,
  S.CLOSE_TRAILER_LOCAL,
  DECODE(I.PRODUCT_TYPE_CODE, 'SA', I.X_PRODUCT_FAMILY, I.X_FG_BRAND) FG_BRAND,
  I.X_WATER_TYPE PRODUCT_TYPE,
  DECODE(I.PRODUCT_TYPE_CODE, 'SA', I.X_WATER_TYPE, I.X_FG_FLAVOR) FG_FLAVOR,
  DECODE(I.PRODUCT_TYPE_CODE, 'SA', I.X_PRODUCT, I.X_FG_SALES_CATGORY) FG_SALES_CATEGORY,
  DECODE(I.PRODUCT_TYPE_CODE, 'SA', I.X_ATTRIBUTE14, I.X_FG_BUSINESS_UNIT) FG_BUSINESS_UNIT,
  S.DEF_ORG DEF_SHIP_FROM_ORG,
  S.OR_INSERT_DATE_PST ORDER_RELEASE_INSERT_DATE_PST,
  S.CUSTOMER_ITEM,
  LOCAL_ACTUAL_DEPARTURE DESTINATION_DEPARTURE214,
  S.DEF_ROLLUP_ORG_CODE DEF_SHIP_FROM_ROLLUP_ORG,
  S.ORDER_TYPE_CODE,
  S.SHIP_TO_ORG,
  S.SHIP_TO_ROLLUP_ORG,
  S.SHIP_TO_SC_REGION,
  S.FIRST_RESCHEDULE_REASON_CODE,
  I.X_ITEM_DESCRIPTION AS ITEM_DESCRIPTION,
  SHIP_WEEK.X_PLANNING_YEAR SHIP_CONFIRM_YEAR,
  SHIP_WEEK.X_PLANNING_WEEK SHIP_CONFIRM_WEEK,
  S.ADDRESS_DESCRIPTION LOCATION,
  S.SOA_SHIPMENT_DATE AS SOA_SHIPMENT_TIME,
  SOA_SHIP_WEEK.X_PLANNING_WEEK SOA_SHIPMENT_WEEK,
  SOA_SHIP_WEEK.X_PLANNING_YEAR SOA_SHIPMENT_YEAR,
  (S.QTY_REQUESTED - S.SOA_SHIPPED_QUANTITY) AS SOA_SHORT_SHIPPED_CASES,
  CASE
    WHEN
      (
        S.SOA_SHIPPED_QUANTITY
        * CAST(
          CASE
            WHEN I.X_ATTRIBUTE5 = 'Unspecified' THEN 0
            ELSE I.X_ATTRIBUTE5
          END AS DOUBLE
        )
      ) > S.PKEQ24_CASES_REQUESTED
    THEN
      S.PKEQ24_CASES_REQUESTED
    ELSE
      (
        S.SOA_SHIPPED_QUANTITY
        * CAST(
          CASE
            WHEN I.X_ATTRIBUTE5 = 'Unspecified' THEN 0
            ELSE I.X_ATTRIBUTE5
          END AS DOUBLE
        )
      )
  END AS SOA_SHIPPED_24PKEQCASES,
  (S.QTY_REQUESTED - S.SOA_SHIPPED_QUANTITY)
  * CAST(
    CASE
      WHEN I.x_attribute5 = 'Unspecified' THEN 0
      ELSE I.x_attribute5
    END AS DOUBLE
  ) AS SOA_SHORT_SHIPPED_24PKEQCASES,
  I.X_ATTRIBUTE14 X_ATTRIBUTE14,
  S.ORIGINAL_REQUESTED_QTY_CASES AS ORIGINAL_REQUESTED_CASES,
  S.ORIGINAL_REQUESTED_QTY
  * CAST(
    CASE
      WHEN I.x_attribute5 = 'Unspecified' THEN 0
      ELSE I.x_attribute5
    END AS DOUBLE
  ) AS ORIGINAL_REQUESTED_24PKEQCASES,
  DEST_IO.X_SHIPPING_REGION SHIP_TO_SH_REGION,
  S.SUPPLY_CHAIN_LOADTYPE AS SUPPLY_CHAIN_LOAD_TYPE,
  CASE
    --WHEN S.STATUS <> 'CANCELLED' THEN NULL                    --Commented by Ankit N on 2_16_2026 to handle CANCELED status
    WHEN
      S.STATUS NOT IN ('CANCELLED', 'CANCELED')
    THEN
      NULL --Added by Ankit N on 2_16_2026 to handle CANCELED status
    WHEN
      S.CANCEL_REASON_CODE IN (
        '03-NIAGARA-OVERSOLD',
        '04-NIAGARA-CARRIER FAILURE',
        '05-NIAGARA-DOCK AVAILABILITY',
        '06-NIAGARA-INVENTORYINACCURACY',
        '07-NIAGARA-SCHEDULING ERROR',
        '09-NIAGARA-PLANNING',
        '10-NIAGARA-MANUFACTURING DELAY',
        '11-NIAGARA-QUALITY HOLD',
        '12-NIAGARA-RAW MATERIAL ISSUE',
        '13-NIAGARA-SHIPPING DELAY',
        '14-NIAGARA-SYSTEM ISSUE',
        '15-NIAGARA-OTHER',
        '16-NIAGARA - FRCST VARIATIONS',
        '26-SPRING-WATER-CONSTRAINTS',
        '28-CARRIER SCHEDULING ERROR',
        '28-NIAGARA-ORDER EXPIRED',
        '29-NIAGARA-ORDER EXPIRED',
        '48-UNAPPROVED LATE ORDER',
        '54-NIAGARA DOCK CONSTRAINT'
      )
    THEN
      'CANCELLED - NIAGARA'
    WHEN
      S.CANCEL_REASON_CODE IN (
        '01-CUSTOMER-CUSTOMER',
        '02-CUSTOMER-CPU CARRIER',
        '17 CSTMR CARRIER UNLOAD DELAY',
        '18-CUSTOMER-VOLUME SMOOTHING',
        '27-CUSTOMER-FORECAST VARIATION',
        '37-CUSTOMER-SUPPLIED RAWS',
        '49-APPROVED LATE ORDER',
        '50-PENDING CUSTOMER RESPONSE',
        '51-APROVED PUSH ORDER',
        '52-CUST REQUEST EARLY DATE',
        '52-CUST REQUESTED EARLY DATE',
        '53-CUST RECEIVING CONSTRAINT',
        '55-CUST RESCHEDULED FOR FUTURE'
      )
    THEN
      'CANCELLED - CUSTOMER'
    ELSE 'CANCELLED - OTHER'
  END AS CANCEL_REASON_BUCKET,
  S.PALLETS_REQUESTED REQUESTED_PALLETS,
  S.PALLETS_SHIPPED SHIPPED_PALLETS,
  S.PALLETS_SHORT_SHIPPED SHORT_PALLETS,
  S.CANCELLED_CASES,
  S.CANCELLED_24PKEQCASES CANCELLED_24PKEQCASES,
  S.CANCELLED_PALLETS CANCELLED_PALLETS,
  APPOINTMENT_DELIVERY_PST DELIVERY_APPOINTMENT_PST,
  DELIVERY_WINDOW_END_LOCAL DELIVERY_WINDOW_END_PST,
  DELIVERY_WINDOW_START_LOCAL DELIVERY_WINDOW_START_PST,
  S.LOCAL_ACTUAL_DEPARTURE LAST_STOP_ACTUAL_DEPARTURE,
  CREATED_ON_DT_SRC_TZ ORDER_CREATION_DATE_LOCAL,
  S.ORIGINAL_REQUEST_DATE_PST ORIGINAL_REQUEST_DATE_PST,
  S.APPOINTMENT_PICKUP_PST PICKUP_APPOINTMENT_PST,
  S.PKEQ24_CASES_SHORT_SHIPPED SHORT_24PKEQCASES,
  S.SHIP_CONFIRM_DATE SHIP_CONFIRM_DATE_PST,
  S.WATER_TYPE_SC WATER_TYPE_SC,
  S.WEEK_NUMBER PROMISE_WEEK,
  S.CRITICAL_FLAG CRITICAL_FLAG,
  S.DEMAND_CLASS_CODE,
  S.AOP_RESULT,
  S.GENPLAN_RESULT,
  S.SHIPMENT_PRELOAD,
  S.SOA_SHIPPED_QUANTITY as SOA_SHIPPED_CASES,
  S.CREATED_ON_DT_SRC_TZ LINE_CREATED_ON_DT,
  S.SCHEDULE_INSERT_DATE,
  S.SCHEDULE_UPDATE_DATE,
  S.OREF_SCHEDULE_UPDATE_DATE,
  S.OREF_SCHEDULE_INSERT_USER,
  S.OREF_SCHEDULE_UPDATE_DATE_LOCAL,
  S.OREF_SCHEDULE_INSERT_DATE_LOCAL,
  S.OREF_SCHEDULE_UPDATE_DATE_PST,
  S.OREF_SCHEDULE_INSERT_DATE_PST,
  S.WITH_DRAW_USER_FLAG,
  (S.ORIGINAL_REQUESTED_QTY - S.ACTUAL_CASES_REQUESTED) AS BALANCE_REQUESTED_CASES,
  S.FINAL_REQUEST_DATE_PST,
  I.X_ATTRIBUTE14 ROLLUP_ITEM,
  S.MTO_FLG,
  S.OSP,
  S.MOSP,
  S.PUA_REASON_CODE,
  S.SOA_SHIPMENT_DATE SOA_SHIPMENT_DATE_LOCAL,
  ---Start: Modified to convert only fusion data to UTC and keep EBS data as is copy---
  --from_utc_timestamp(S.SOA_SHIPMENT_DATE, 'America/Los_Angeles') AS SOA_SHIPMENT_DATE_PST,
  case
    when order_number like '4%' then from_utc_timestamp(S.SOA_SHIPMENT_DATE, 'America/Los_Angeles')
    else S.SOA_SHIPMENT_DATE
  end AS SOA_SHIPMENT_DATE_PST,
  /* case
    when
      order_number like '4%'
    then
      from_utc_timestamp(S.FINAL_CUSTOMER_AGREED_DATE, 'America/Los_Angeles')
    else S.FINAL_CUSTOMER_AGREED_DATE
  end AS FINAL_PROMISE_DATE_PST, */
from_utc_timestamp(
        S.FINAL_CUSTOMER_AGREED_DATE,
        CASE 
            WHEN LOC_TZ_D.TIME_ZONE_GID IS NULL 
                 OR LOC_TZ_D.TIME_ZONE_GID = 'Unspecified'
                THEN 'America/Los_Angeles'
            ELSE LOC_TZ_D.TIME_ZONE_GID
        END
    ) AS FINAL_PROMISE_DATE_PST,
  case
    when
      order_number like '4%'
    then
      from_utc_timestamp(S.LOCAL_ARRIVAL_DATE_214, 'America/Los_Angeles')
    else S.LOCAL_ARRIVAL_DATE_214
  end AS LAST_STOP_ACTUAL_ARRIVAL_LOCAL,
  --from_utc_timestamp(S.LOCAL_ARRIVAL_DATE_214,'America/Los_Angeles') AS LAST_STOP_ACTUAL_ARRIVAL_LOCAL,
  ---END: Modified to convert only fusion data to UTC and keep EBS data as is copy----
  S.ORDER_RELEASE_INSERT_DATE,
  S.ORDERED_ON_DT,
  S.EARLY_PICKUP_DATE
FROM
  NBL_FUSION_DW.FACT_SERVICE_METRICS AS S
    JOIN NBL_FUSION_DW.DIM_INV_MASTER_ITEMS AS I
      ON S.SK_ITEM_ID = I.SK_INV_MASTER_ITEMS_ID
    JOIN NBL_FUSION_DW.DIM_HR_ORG AS DEST_IO
      ON S.SK_X_DESTINATION_ORGANIZATION_ID = DEST_IO.SK_ORG_ID
    LEFT JOIN NBL_OTM_DW.DIM_LOCATION_TIMEZONE AS LOC_TZ_D
      ON S.CUSTOMER_LOCATION_GID = LOC_TZ_D.LOCATION_GID
    LEFT JOIN NBL_FUSION_DW.DIM_MCAL_DAY AS SOA_SHIP_WEEK
      ON CAST(S.SOA_SHIPMENT_DATE as DATE) = CAST(SOA_SHIP_WEEK.MCAL_DAY_DT as DATE)
      AND SOA_SHIP_WEEK.MCAL_CAL_ID = 'Planning~42'
    LEFT JOIN NBL_FUSION_DW.DIM_MCAL_DAY AS SHIP_WEEK
      ON CAST(S.SHIP_CONFIRM_DATE as DATE) = CAST(SHIP_WEEK.MCAL_DAY_DT as DATE)
      AND SHIP_WEEK.MCAL_CAL_ID = 'Planning~42'
WHERE
  1 = 1
